apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-snapshot-controller
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/disabled: "true"
spec:
  path: ./kubernetes/apps/storage/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: snapshot-controller
      namespace: storage
  interval: 30m
  retryInterval: 1m
  timeout: 3m
