apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: odoo
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: odoo-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HOST: postgres17-rw.database.svc.cluster.local
        PORT: "5432"
        USER: "{{ .ODOO_POSTGRES_USERNAME }}"
        PASSWORD: "{{ .ODOO_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: odoo

