---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-r2
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "0 2 * * *"
  restic:
    copyMethod: Snapshot
    repository: ${APP}-volsync-r2
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-zfs}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-zfs}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-zfs}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-568}
      runAsGroup: ${APP_GID:-568}
      fsGroup: ${APP_GID:-568}
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 1
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-addons-r2
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "30 3 * * *"
  restic:
    copyMethod: Snapshot
    repository: ${APP}-volsync-r2
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-zfs}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:-zfs}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-zfs}"
    moverSecurityContext:
      runAsUser: ${APP_UID:-568}
      runAsGroup: ${APP_GID:-568}
      fsGroup: ${APP_GID:-568}
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 1
