---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres14
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: local-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  backup:
    retentionPolicy: "30d"
    barmanObjectStore: &barmanObjectStore
      wal:
        compression: bzip2
        maxParallel: 4
      data:
        compression: bzip2
      destinationPath: s3://oracle-cnpg/
      endpointURL: http://s3.skym.fi
      serverName: &currentCluster cnpg14-v2
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
  bootstrap:
    recovery:
      source: &previousCluster postgres-default-v1
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster
