---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./coredns/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./talos-ccm/ks.yaml
 # - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./reflector/ks.yaml
