---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        args:
          - --v=9
          - --timeout=90s
          - --worker-threads=10
          - --csi-address=/csi-data/csi.sock
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=true
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1

      # distributed support is not yet ready
      externalResizer:
        enabled: false

      externalSnapshotter:
        enabled: true
        extraArgs:
          - --leader-election=false
          - --node-deployment=true

      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.9.3
        imagePullPolicy: Always
        logLevel: debug
    node:
      driver:
        image: ghcr.io/democratic-csi/democratic-csi:v1.9.3
        imagePullPolicy: Always
        logLevel: debug

    csiDriver:
      name: "org.democratic-csi.zfs-local-dataset"
      storageCapacity: false
      fsGroupPolicy: File

    driver:
      config:
        driver: zfs-local-dataset

        zfs:
          datasetParentName: tank/k8s/volumes
          detachedSnapshotsDatasetParentName: tank/k8s/snapshots
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetProperties:
            recordsize: "1M"
            compression: lz4
            atime: off
            overlay: on

    storageClasses:
      - name: zfs
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: zfs

    volumeSnapshotClasses:
      - name: zfs
        deletionPolicy: Delete
        parameters:
          detachedSnapshots: "true"
        secrets:
          snapshotter-secret:
