apiVersion: v1
kind: Secret
metadata:
    name: bunny-api
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ZLYHVmBIslF6uGp6bSd/6UAiH6qn/yXfLzcwoT7xRUZQduW8/XZ1v19SnNFhwm97gGxyb9PRvLVvnFGl5oeWE9RWUIO1QuPr,iv:5TFA8hahbu3rK79iZdEemNV2SmpXnC4dBFp9fbHy0jE=,tag:OWeuPibuEcpQiPnS0XoJow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZzR6ZXBvNnRYcFJBU2ZB
            bTJQbUgyYzJtNmpJQkJlTWpYcWFZTk56UlZBCnFsQzhOYmlQdXY1TnlUV3NYL1ls
            SmRaNUE3RzlPbE4yZWhTTmJzYTBxeVUKLS0tIGVSTjhncXNuRjZlN1pYWEQwOFp1
            RGlPV2o0bjlVMSszNEpweFdQNUdCMDQK36dZnv/I8kvoIyt89UM1DDAkgKeHKpSi
            u3O5O+Jxyuq49py1NdT0KNo4pL0W5LgocH3ptjpDEyuRFFizhep2xA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSTMweDM1QU8wNVpGaFVB
            aUViNndsSG9tb0xZVjZHRVhRYjQ4YTdzZm5FCjVvRWhVdWpiZmg3UlgwWmlyY0xW
            L1l2S0dZUUEvdHl6d29LbXZxYTRHOTAKLS0tIG5yUG4vQld2Um1SZkpQT0RMc1Fp
            VTRkV242YU5lNTdjblVsMnp6UTJaMDAKSix9Tj7XP0x4jri/G7qPL/yp8PfPT0Yu
            L2Dxl5F7HxYbDSIV4PlpnDORmuEmxCZRDdTucOSwBdswfR/s3gJ+ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1egjvlc7ss968wa2fhmntua0v2cyfual2hr329tptgk6gl3tkqsxs7dz3zc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:41:28Z"
    mac: ENC[AES256_GCM,data:UW3rudpQeSHZx1YEmYVzaEEWVfVu8P+IwMrdJr4hhZ18pG57MIKGxFhogSvAwyual5OCpT7RrH77Bi6cY1cLz2kk/3jcT2LZw/WZqvgaMavIn92VXVqLnsAsE8gbyZ8suqMnsEhxljpc+yoP4PXS28gm3aVTbt5rNw1KuhfUuHU=,iv:fiMAh8UpTHFeeSxdAtTGDWQpPhb6Giqo2qoyjJYOTmc=,tag:SezBmFPM2FU67bajaOvgXA==,type:str]
    version: 3.13.3
