---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes"
  BOOTSTRAP_DIR: '{{.CLUSTER_DIR}}/bootstrap'

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  MINIJINJA_CONFIG_FILE: '{{.ROOT_DIR}}/.minijinja.toml'
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"
  K8S_AUTH_KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  TALOSCONFIG: '{{.BOOTSTRAP_DIR}}/talos/clusterconfig/talosconfig'

includes:
#  bootstrap: .taskfiles/bootstrap
  brew: .taskfiles/BrewTasks.yaml
  cluster: .taskfiles/ClusterTasks.yaml
  externalsecrets:
    taskfile: .taskfiles/externalsecrets
    dir: .taskfiles/externalsecrets
  volsync: .taskfiles/VolSync/Taskfile.yaml

tasks:

  default:
    cmd: task --list
    silent: true

  # Ref: https://github.com/go-task/task/issues/608
  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
