apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
    image:
      repository: &image ghcr.io/onedr0p/volsync
      tag: &tag 0.10.0@sha256:104fa2bca5f00125a15d3f19d4cd5b25f6fb3ac69b57bfbff8431c8e6ab6b27c
    restic:
      repository: *image
      tag: *tag
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: volsync
            spec:
              template:
                spec:
                  containers:
                    - name: manager
                      volumeMounts:
                        - name: tz-config
                          mountPath: /etc/localtime
                  volumes:
                    - name: tz-config
                      hostPath:
                        path: /usr/share/zoneinfo/Europe/Stockholm
                        type: File
