apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync
spec:
  interval: 30m
  chart:
    spec:
      chart: volsync
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: snapshot-controller
      namespace: storage
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
    image:
      repository: &image ghcr.io/onedr0p/volsync
      tag: &tag 0.10.0@sha256:2b783852bafa859787618b86eef8da940e645760723ab58f91ca76ac7f37d010
    restic:
      repository: *image
      tag: *tag
