---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app external-dns-external
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
   fullnameOverride: &name kapsi-external
   podAnnotations:
     secret.reloader.stakater.com/reload: externaldns-kapsi-secrets

   domainFilters:
     - piped.fi

   env:
    - name: EXTERNAL_DNS_RFC2136_HOST
      value: "ns1.kapsi.fi"
    - name: EXTERNAL_DNS_RFC2136_PORT
      value: "53"
    - name: EXTERNAL_DNS_RFC2136_ZONE
      value: "piped.fi"
    - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
      value: "true"
    - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
      value: skyexternaldns
    - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
      valueFrom:
        secretKeyRef:
          name: externaldns-kapsi-secrets
          key: bind_rndc_algorithm
    - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
      valueFrom:
        secretKeyRef:
          name: externaldns-kapsi-secrets
          key: bind_rndc_secret

   policy: sync
   provider: rfc2136


   sources:
     - ingress

   txtPrefix: "k8s-tmi."

   resources:
     requests:
       cpu: 16m
       memory: 90M
     limits:
       memory: 90M

   postRenderers:
     - kustomize:
         patches:
           - target:
               version: v1
               kind: Deployment
               name: *name
             patch: |
               - op: add
                 path: /spec/template/spec/enableServiceLinks
                 value: false

