apiVersion: v1
kind: Secret
metadata:
    name: externaldns-kapsi-secrets
    namespace: networking
stringData:
    bind_rndc_algorithm: ENC[AES256_GCM,data:lRuqO1KTIcb5EiQ=,iv:7RfiMpCkpep0HfuIeGFHfg1rB5DV1oEMjtKdLgLXCH4=,tag:fxhdW7oQi4yauuXBI6afPw==,type:str]
    bind_rndc_secret: ENC[AES256_GCM,data:Wt5bUWo8Pv4hU3Xi7a8oIgiwbMc9YYyXbTnFgQfH05o51azC9wAwPbHhPlw=,iv:PyIlaHHKwDZFEuCyVaGwAYb4NJCzCn3ahnc3I/77ijM=,tag:JfZl3zu+xEJWoYjIRpIj6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeUV3SWhlZGdTTjE0T1dq
            RmVGWGZQM0x6Y3hMdzRvNXE4QTlIQTFJWkJnCmsxQ3crNEZSeTBSWjhVSkZveU9V
            YnFnb21ZdmpZWW9Da1lWT05OWjcza1EKLS0tIHZtcGZZdWpzZEE5R1R5UFpnaFVz
            bUpBbGkvQzdIRkYvM2I4YmxoY0VoZ28K05NqgscCxprFszrxEcTXKAGjqKb8ks04
            zvfX9nQqdAE7kzvuEqZUhr8GEtroEZ5MZL4xA43dqAMMol8J24Jfog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1egjvlc7ss968wa2fhmntua0v2cyfual2hr329tptgk6gl3tkqsxs7dz3zc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdVVzSms4b1p4dTh5aFF0
            NDIwUGYwRVZmc1F2L2FBckI2cXo3eDlDM1FzCjNVVWZENmNtMDA2NGVpVmJGNmhi
            WXNsVUNLNzJQNlBaTUx4eGxhRzRENFUKLS0tIFNnZ3V6MXdPMnpzNVBkd2NUVEd1
            TFVaQ0ZYQkRHZ3UrRThzbW9tZ3JFMlUKTeC1YHbqH8KbNo9mpkctrGciHH2G1Ml+
            1ZKj8dE39gE5r8xO3xFQ1P/y605vYgqy4xSFY2dL2IC9Vy/S7mo/wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T13:45:36Z"
    mac: ENC[AES256_GCM,data:USbik8F3MYuSSnVggryijUNrJEcGSuvMAgChUmVoFBdPd89EOfR5hx1y7EMaPjfAmZwpQn2va7UB+BRd0u0uiYUX7DMEbPo0eYa3MU1a15oHDqN7OJJEFHZQKYWSToUTNGeP19+WFaz5QuevOAPNrmwQ6I5+hWYtZ72paOMxtsQ=,iv:EfxiwKg63c86D5JqnyxwfVNk+u2UXcMuiPNxgeaKP/s=,tag:/W6eY/aIV6PRpiN5+p/65g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
