---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-odoo
  namespace: flux-system
spec:
  dependsOn:
    - name: database-cloudnative-pg-cluster
  path: ./kubernetes/apps/default/odoo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: odoo
      VOLSYNC_CLAIM: odoo-config
      VOLSYNC_CAPACITY: 1Gi
      APP_UID: "568"
      APP_GID: "568"
