apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:HK2gNx7o5VsboHdX8lTF2yi06J/V2YfCpbPGdMy2pHn3Gyxc83zK5Q==,iv:S7bStXMy+Yade+YM257hc07SByJDuzmHhiH2VyDEXao=,tag:TV4vCAXjdbQcHpeBWusdjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SWQzRE1GRjhCazFJQUl5
            dUh6VmJ4L1JvcGQ4cTdEaFZEL3RNSkgwQUNvClNnZ05tMjFXT0c1ak91cndsR08x
            UTVqMGswUWhmZExiclJJeXBGUGFsWnMKLS0tIGVrd0NHVlV2aGl5S25oMUl3eHNu
            alFKZzNxMHlGcUhxWkJOejFFYzM3NFEKc47GXUCuk2C58MmcVu4LfhIe4JGwaEtf
            2WJUL7VAEQIvoTWInOqlHnf+m3XMsBrnoD8xLTVAuIXy/T8l0lT7bQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1egjvlc7ss968wa2fhmntua0v2cyfual2hr329tptgk6gl3tkqsxs7dz3zc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycjc0RFFVdGUzY2IzbUdP
            bUdSWXpuVys4QmQzYUVwWXgvMDFKeWEwc2cwClZsckNJNXRSYmRtUG9UVTRQc0sv
            RDE2czdWOUNza0luR2dqbXZRd1lYOXMKLS0tIFNkNW11a21NdW9VOTdwN1ZXek1l
            SHg0N1JzVVhDTzUvL3NQZnJXVk9tZ2sKt+SkZ2x3SDmeYwCP21BHayzCz1BgHFxM
            SY1VeH6eiFqvcIb1plWRDg/ydrQQ9RtVXGBDDuKuB7y5v/52kRetIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T13:46:46Z"
    mac: ENC[AES256_GCM,data:x79pzpJzP9ak3SqNAreVTs2vfgJnTWLpTXtWchlH67WXZdyRN7CPYA5pTQ+vcEjWu4eZ7RE6wqayuWMUmtlh3Xgb3UwjY9UhcO8E19CBq5ttCoHOgKv/6HYuF751Elb5wYeltSblqmnkHusWD5T8oxQQ5hWRnSh/hpxJd0r57LE=,iv:Jqj41EX9l1yFGpDgbtOBQzWsiaIAAIV43zz8lYlJFpM=,tag:j7uMR3lUsRpc1z4wTPZF2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
