apiVersion: v1
kind: Secret
metadata:
    name: kapsi-tsig
    namespace: cert-manager
stringData:
    secret: ENC[AES256_GCM,data:NX2B8UaYmue5uXWnpSMW4CBIuyAhfEcvyNdJyDuPmBcck1e6oep0SKZPwv0=,iv:0GJBrXcKOUosiY14VEvDMoo5W/BUIFGXw5Q3Mp1G0gs=,tag:8uT2Y+sho1/m0MI86lfBmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud1RWaTljVjRFWnZqVmNI
            dEtUMTU4WTJ3S0QyVmoxQXdiVVA0Y1NnQkVvCkdNK3JyL3crOG9TV0NVT2xhYjF0
            STIvYXhacjdIUnpsV1I2cWFaa1Y5Vm8KLS0tIDZrS3haM0N4RThzWHlhMU5SSWtY
            NHZyVTR3K1Q2Y0pzVXMzMDh4UzNFdUUK2K1vck5dTnYdnWgqAahrr6fKIc1MHiHM
            X17MgTPi/AImSbTYyHZTDO7I1FVw/Ddyx8whXIzCVDQ6QqOVqrMaJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1egjvlc7ss968wa2fhmntua0v2cyfual2hr329tptgk6gl3tkqsxs7dz3zc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYlpHbWt5ZjZLMTVMZXF1
            dXhuV0VzamdFYVVYNkkxWHd0MnN2bmIwQkNBCjdVZ2RNRTZpVDdMYTgxQk8rWUxx
            U0RGbFE4NzBNTEI4K05nekJmakZla0UKLS0tIGFNcEo4QWpUWC83WkV2TnZBczd4
            U29WYStiYUdiOFdabXM3eFd5RlRKanMKzjYOCUG+P14EfNQCR5sjeNMuSSPt3A5A
            +p5u42/h6hQ/ssoaB/ZE8Q8edL15fcRVF3nkSUE/oLemLo5U2G924g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T13:46:50Z"
    mac: ENC[AES256_GCM,data:gvLMqmATbp2t2qzBiXiPRfxAY+iP4U5f1jVEuiPkDK3C26KNG3Tnkcyme7x31xty7NrzVPPgHxE8oK/uivdjsk8mOhZhQBvwFCCiG8EM6fL0JzNKAvpwc7P3MGXnUuVzUfq3GHbFlsueJG5ip5Xs8AJCBJn13Izxoh8gNEbFaJE=,iv:3HauPcdpraMFGEmODMUS+UYZOww2dvkA2Z6H0Eq4UPE=,tag:aHYxaDACezYgwYPXrQt4RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
