apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:wQ1fBW6DrmXpjCFFDIheM/V81+/e3NuwFijNdSmHvHMVaFfv+IzRAA==,iv:PbFq8MdXa0DSajuEqWgKayas2OKiDRWtaEH9BXPLtj4=,tag:pY3ofyEXPSIooaF3snguuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM211ZmpiNWp3bjlHUzh2
            a3FqRVVIRWUwQ2RwZTBPVmQ5bCt6MEhDNEMwCkpQd2lsYk9qQTV5NjN5YTUxdFpo
            V2dUSHErUnMvY3JxSnA4eXdqWFExWFEKLS0tIEdIM08vV003bmVtQUlIeWY5QVdY
            aWFFVkMveXg2MzQ4T3BBUSsyQWgwR3MKzIE/nlTCQIUUY6pbk//Ii1qA6WYhIDLN
            xJRJlREJ42QvC2tzIl3EZ6BUD/bmAdPeQT6DljWdMYFn666nbpbv1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T05:50:57Z"
    mac: ENC[AES256_GCM,data:AQH6gQ+YyDor0WFyL+gK4ThShIbaeRI+HO5Rgamf8u/YcUoZB2h84hH5d8NfNShxiOlP3dmPj/SmCMOetpYSpbAxIm7CFeD4genbDVmtsjGxMXLIxR7o9Dj43vYfnMxUPg1weei4Ke28nAZFL2xayA1MDT5gDnBQgrdx09eOGH8=,iv:pXm7hmP5x9wsJiwJBiUVDWPFyb+ubo1+aOcghzu899E=,tag:P6aJtr2Y3GuGQKzeGsqDqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
