---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 2.8.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    replicaCount: 1

    crds:
      # -- If true, create CRDs for Cluster External Secret. If set to false you must also set processClusterExternalSecret: false.
      createClusterExternalSecret: true
      # -- If true, create CRDs for Cluster Secret Store. If set to false you must also set processClusterStore: false.
      createClusterSecretStore: true
      # -- If true, create CRDs for Secret Store. If set to false you must also set processSecretStore: false.
      createSecretStore: true
      # -- If true, create CRDs for Cluster Generator. If set to false you must also set processClusterGenerator: false.
      createClusterGenerator: true
      # -- If true, create CRDs for Cluster Push Secret. If set to false you must also set processClusterPushSecret: false.
      createClusterPushSecret: true
      # -- If true, create CRDs for Push Secret. If set to false you must also set processPushSecret: false.
      createPushSecret: true
      annotations: { }
      conversion:
        # -- Conversion is disabled by default as we stopped supporting v1alpha1.
        enabled: false
      # -- If true, enable v1beta1 API version serving for ExternalSecret, ClusterExternalSecret, SecretStore, and ClusterSecretStore CRDs.
      # v1beta1 is deprecated. Only enable this for backward compatibility if you have existing v1beta1 resources.
      # Warning: This flag will be removed on 2026.05.01.
      unsafeServeV1Beta1: false

    serviceMonitor:
      enabled: false
      interval: 1m

    webhook:
      serviceMonitor:
        enabled: false
        interval: 1m

    certController:
      serviceMonitor:
        enabled: false
        interval: 1m
