---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: zfs-localpv
      version: 2.6.2
      sourceRef:
        kind: HelmRepository
        name: openebs-zfs-localpv
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    crds:
      zfsLocalPv:
        enabled: true
      csi:
        volumeSnapshots:
          # Installed with the Snapshot Controller
          enabled: false
