---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: zfs-localpv
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: openebs-zfs-localpv
        namespace: flux-system
  install:
    timeout: 30m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    crds:
      zfsLocalPv:
        enabled: true
      csi:
        volumeSnapshots:
          # Installed with the Snapshot Controller
          enabled: false
    zfsNode:
      encrKeysDir: /var/openebs/keys
