---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    timeout: 30m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: true
      replicated:
        mayastor:
          enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
    zfs-localpv:
      enabled: true
      zfsNode:
        encrKeysDir: /var/openebs/keys
      crds:
        zfsLocalPv:
          enabled: true
        csi:
          volumeSnapshots:
            enabled: false
