---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs
allowVolumeExpansion: true
parameters:
  fstype: zfs
  poolname: tank/k8s/volumes
  recordsize: 128k
  compresion: lz4
  dedup: off
  thinprovision: yes
  shared: yes
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
