apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: piped-vpn
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: piped-vpnconfig
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WIREGUARD_ADDRESSES:  "{{ .PIPED_VPN_ADDRESSES }}"
        WIREGUARD_PRIVATE_KEY: "{{ .PIPED_VPN_PRIVATE_KEY }}"
        WIREGUARD_PRESHARED_KEY: "{{ .PIPED_VPN_PRESHARED_KEY }}"
  dataFrom:
    - extract:
        key: piped-vpn

