---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talos-cloud-controller-manager
spec:
  interval: 4h
  maxHistory: 2
  chart:
    spec:
      chart: talos-cloud-controller-manager
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: siderolabs
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    enabledControllers:
      - cloud-node
      - node-csr-approval
      - node-ipam-controller

    daemonSet:
      enabled: true
