---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app invoiceninja
  namespace: flux-system
spec:
  targetNamespace: &ns default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/default/invoiceninja/invoiceninja/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: invoiceninja-storage-pvc
    - name: invoiceninja-public-pvc
  postBuild:
    substitute:
      APP_NS: *ns
