---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-meta
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux/meta
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  # Flux repositories under this need flux-system hardcoded as namespace for Renovate lookups
  targetNamespace: flux-system
  timeout: 5m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-meta
  interval: 30m
  path: ./kubernetes/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: cluster-settings-user
      - kind: Secret
        name: cluster-secrets-user
  patches:
    - patch: |-
        - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
          namespace: not-used
        spec:
          interval: 10m0s
          retryInterval: 2m0s
          timeout: 5m
          wait: true
          sourceRef:
            kind: GitRepository
            name: flux-system
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substitute: {}
            substituteFrom:
              - kind: ConfigMap
                name: global-cluster-config
              - kind: Secret
                name: global-cluster-secrets
              - kind: ConfigMap
                name: cluster-config
              - kind: Secret
                name: cluster-secrets
      target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        version: v1
