apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: windmill
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: windmill
      version: 2.0.316
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    app:
      annotations:
        secret.reloader.stakater.com/reload: &secret windmill-secret
    windmill:
      # renovate: datasource=docker depName=ghcr.io/windmill-labs/windmill
      tag: "1.426.1"
      baseDomain: &host wind.skysolutions.fi
      baseProtocol: https
      appReplicas: 1
      lspReplicas: 1
      multiplayerReplicas: 1
      app:
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
      workerGroups:
        - name: "default"
          replicas: 2
          resources:
            requests:
              memory: "1028Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
        - name: "native"
          replicas: 1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN_2}"
      tls:
        - hosts:
            - *host
    postgresql:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: WINDMILL_POSTGRES_URL
      targetPath: windmill.databaseUrl
  #postRenderers:
  #  - kustomize:
  #      patchesStrategicMerge:
  #        - kind: Deployment
  #          apiVersion: apps/v1
  #          metadata:
  #            name: windmill-app
  #          spec:
  #            template:
  #              spec:
  #                initContainers:
  #                  - name: 01-init-db
  #                    image: ghcr.io/onedr0p/postgres-init:14.10
  #                    envFrom:
  #                      - secretRef:
  #                          name: *secret
