---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-piped-helper
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/piped/bg-helper
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
