---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-piped
  namespace: flux-system
spec:
  dependsOn:
    - name: database-cloudnative-pg-cluster
  path: ./kubernetes/apps/default/piped/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: piped
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
