---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-piped
  namespace: flux-system
spec:
  dependsOn:
    - name: postgres17-cluster
    - name: default-piped-helper
  path: ./kubernetes/apps/default/piped/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: piped
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
