apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .POSTGRES_PASSWORD }}"
        username: "{{ .POSTGRES_USERNAME }}"
        aws-access-key-id: "{{ .POSTGRES_AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "{{ .POSTGRES_AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: cloudnative-pg

