apiVersion: v1
kind: Secret
metadata:
    name: github-receiver-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1cQqWTychr/W97p2HPjZEpHzaLy8sH5oJ3iiOKz0UNdvpmJjviELXQ==,iv:tE7/cfLoRkeqXklfQxsQYTWUAIlpZr5js+DVZ+Mx3vc=,tag:XHgzKfEOPI8jl1ng6TojaQ==,type:str]
sops:
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdHZyOStjcEVHYTB5ZGd4
            UVloeElBSWRxV2tmV3lXYlBsT0RIa09zcDFJCmRrN3kya2tmSzhoRnVRTkVpM0VP
            NFJCVGpUTHhRcVZZLzZaVlJ1REd4QncKLS0tIE5TeEFyWnA1M3V6OGJxRU1XbW9R
            bUhQNWdJemduVDhBTHJyQlBBdW5sbDgKj1rQxuGOVgXZulWGVUcyiSKatWZLp0vi
            3++2bsKv+UsqYAwx3/7pyJIpOSk+XT7OF8ii/Owld3poiySaMqalhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1egjvlc7ss968wa2fhmntua0v2cyfual2hr329tptgk6gl3tkqsxs7dz3zc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRUVnTDk2QjhzRkJrRXVW
            bllsdFhEMmpXQkZtMjA5Skx2NEpRSmh3WHdRCkQ4MHdKRFFabjY1QWpyTXVPNmIx
            QTlDdFMyUUpGSnRNdG5NSG9JQTNFYTQKLS0tIHlrVENoL1hzdDd4djJGTVIyUHRh
            Yzl2QmcrVXVSWnFjUFA3QklmbHZvZDAKx77djsk5zOqLtIOnpxP5j3ItCe/j/CH4
            oOOoFShoaqi7hT33xE/ENar6WB2U5WptMec8pDbcL/OPNI7/8bFz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T07:37:22Z"
    mac: ENC[AES256_GCM,data:0u+vnuWg0Co0B2fyyI3IhsJRt1269mDfingT8Btep1NFfY4LaFnfob79vArmchjU9XC6cDJu6Xopi+RocUmeeOALoqt9pu/0AGOyCvxRpYk03z9cSByH/Y1DehWj1oeBp0kKwu7hMlfBXALOiRTmiJYEB2gIf3UOVnX8uwYRm8Y=,iv:guwX67w1xKQEN+D/QKJoV+Ev9l9yKAzdOwV03QIw8wg=,tag:0ZzZEjIA+HhXJZmqrURpEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
