---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  labels:
    app.kubernetes.io/name: harbor-registry
    app.kubernetes.io/instance: harbor
spec:
  storageClassName: zfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
