apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1U4UNM3qkHvwvv1fbDlNpaIbhFlaj470YuewBXK9BRdFjTVU,iv:LCPMopLMEAqHMsEWicjlQ1HFHF35TCFqwdDYB8lsb2A=,tag:RSuB3NELc9IBbsRBKXujgw==,type:str]
    credentials.json: ENC[AES256_GCM,data:nRZj/cmf/u4XAz/VGZL2WwjXTwm7AM/+F3/w97n6Q0aq9/bukq9h8/JeZrmPU/Vn9WEaXBTvZNosNOeopAMh7mF0Tj6bADWYCS3uzv7ZumU69PzzwI3wVv6X988nLnteXxqgaFjWMo82oQlcEUFh+ceI9pfL6WXUXvziCTs/XrWOs1grll7z6afyn4XzE8WejJd41wAxg8ZkSfGD2IW8NnZZkm+5UsX8bEVeeDHhEw==,iv:ran3X06l5VeVeQCrS3+bc4g/9m/5o6euf00XAgu5VxY=,tag:9hzFUFqBfYxqLm7A8XYFyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUVAzQVd4c1pYRjdVZlF5
            N1V0cm03clhhb3V6dFFxNWozMDdHYXZPd1ZvCk9saGlzTDh5bmgrbC9iWVBMQ0gv
            ZTN2RVpuZm44V2FlSnF5NTMwZHMrbzAKLS0tIHdMUm1jdjZEWWFZb0RLV0ZrTGU3
            SWV6ZzgwanhVeDdMUnBhclhHN1dWRE0Kru5MjDvcM1nYiMv3y2WOOlIPYESRRhG7
            E48p7mOFREFLA5vaD+dUaXKWIfLQeBc6fCwHrSqp0xX4TvM71YlBhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1egjvlc7ss968wa2fhmntua0v2cyfual2hr329tptgk6gl3tkqsxs7dz3zc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRGk4QURGOGpGa094dE1W
            Y3RheXJ6U0hjOFpWZ0kzOTl4ZXlBV0VpdGt3CnppeDE5b0pnVlg5aldFSUwrQytB
            Yis4VFJ5dmROblh6dWs3V3N1cXpLRncKLS0tIE1oRURIUTVBWFRwZFQ4d0tTS3V6
            S2JsQlpPaUJ6ODBMNW13TjZtbG5uUWcKei3OofsiGby9QQWHoGd8vu0hrROJm/EV
            Bs6ZQSBVI/uBtE3S9ZLULf1GYgacXBNfJI32g30xKeI2Bs6JWxgOMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T13:47:48Z"
    mac: ENC[AES256_GCM,data:usRNTT4vaFbjYI2n7EwT/VrGk/dxd98rivOZ0rEo2AqKtLWMFi/cNRsXbwpyiAzi1PgJ3TipsgtsWLEhQTHZyMlvOV0T7i9Bj+2vDqh1cvk65A6m+WxSuj67Llpoup6irNw8ypmUOd4UR3y2QRPuDseuGb7OaC5Zl3VXZaNuT9E=,iv:PJEG6W0kmndEXJjAUOFBijQundjmOnXu2y3REkAgyuM=,tag:S1imU/nPtkUDzySq9Gmmzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
