apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app piped-bg-helper
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: uninstall
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
    controllers:
      piped-bg-helper:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          bg-helper:
            image:
              repository: registry.skysolutions.fi/docker.io/1337kavin/bg-helper-server
              tag: latest


    service:
      main:
        controller: piped-bg-helper
        type: ClusterIP
        ports:
          http:
            port: 3000
    ingress:
      main:
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN_2}"
        hosts:
          - host: &host "helper.piped.fi"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
