---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apprise
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      apprise:
        containers:
          app:
            image:
              # https://hub.docker.com/r/caronc/apprise
              repository: registry.skysolutions.fi/docker.io/caronc/apprise
              tag: 1.1.8
            env:
              TZ: "${TIMEZONE:=Etc/UTC}"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      app:
        controller: apprise
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: nginx
        annotations:
          hajimari.io/icon: bell-cog
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
          nginx.ingress.kubernetes.io/auth-realm: 'Access restricted - private instance'
          external-dns.alpha.kubernetes.io/target: "ingress-cf.${SECRET_DOMAIN_2}"
        hosts:
          - host: &host apprise.${SECRET_DOMAIN_3}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    # TODO: volsync
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Mi
        storageClass: local-hostpath
