apiVersion: v1
kind: Secret
metadata:
    name: towonel-agent
    namespace: networking
stringData:
    TOWONEL_INVITE_TOKEN: ENC[AES256_GCM,data:UGot32X08FRYPLJdLCG0ODfNyCdO77GdntTWDyA8qt5k/9lkK+dRF2Z4kJGKd2ZCsQ+cy01EXpkUT9aSDa+aXrWYAbEkSt+hv0OTmgfEP1Z5dydhY/CSma+T70N32X1fpWw4mYZipJYyMCDLIG9jj9Al8aRWM/k7uir3K9zdqaV/FUbUKGC+QOJr95+/CMG4/woBuPZhPA==,iv:zdE13J5tRmSX2KQM4TSvUu2HYpXrEHyH37LJ0hKGf5M=,tag:boDYSqCCUZpYZDQImAlA8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVnd4UHFwMitUMUtZT1J3
            Wm44clA1czE0RVFRcURhLy9jbUREOUlTaXlFCml0Nkl2NjJMcDZGOEFTM2dNNFF6
            MEhVZHNZbGQzVWx6Y08yMFJWdXBma3MKLS0tIEZhTkdPS0NHN1ZMZlhVZXF0d1lX
            clhWWE5iZnhLZWM4cHVHSFZhS0dib0kK+GIA+qpyBZmQYZ8aGEWs1VIu5Pwj2mY2
            Ztjnm7dTa/tSatw5u0rIVMCwZIjg0ebeLNBMocir8dA9fpEg7dMw7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7uy452klcxxq9dcagvlfts2q5vax0pkfan4t3ss32n9q3kc2gyskm3hff
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UmZPYWpiY0w2UGVxT0NN
            dFJ0d0t2cWJNM0gwYkUyWjVEQ3duL0E4SEJBCnZ4cXlLRHhURWtyQ0pPNXR3bTRC
            aGZlMk9hSDdGTkF3T0wybkdjVlZUNmsKLS0tIHJHdjJVUURCVkYwVFlyRno5UzRt
            QWhTR2E2ZTlwdCs5T2xzZW1EekpLYk0KnvTcVthYr3lmiaT5TKb12qDd0ZbIzOBy
            Pte9xfzBfiP76U+5Sn+qXbJkoTNi2Q6lvovHgWNdWLW9Id03xVCYuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1egjvlc7ss968wa2fhmntua0v2cyfual2hr329tptgk6gl3tkqsxs7dz3zc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:20:16Z"
    mac: ENC[AES256_GCM,data:YW2Yfz7UuA/oobXIGqJib5nePDw/9ypPqtkeGUqT0xHDqkDSC2Yk+DPWrd+GtUwYWajmlwb3D9/Itnc+0XvsrUO7dKB6r/TN4CHfR70mlUrDNnSPimdwjmfG89xfb5WWm4KA2zOy5A0+TuVsBbSHBoRK5igP5BqXihp26ZiLc4w=,iv:xi+6DkmNx7zJdlQwePJxSg3cEECl5SPN3GXTLcz1lkA=,tag:BGJr1xk9hgHuRmtf6qUUaw==,type:str]
    version: 3.13.3
